### ISSUE TITLE
登录ARL使用用户名admin密码arlpass，提示用户名或密码错误，使用密码honmashironeko仍提示错误，重置密码提示没有arl_mongodb这个容器，请问如何解决

### ISSUE THREAD

**Issue by 397332130** [Aabyss-Team/ARL#10]
## 描述问题
登录ARL使用用户名admin密码arlpass，提示用户名或密码错误，重置密码提示没有arl_mongodb这个容器，请问如何解决
请在此处提供对问题的清晰而简洁的描述。

## 环境信息

- 操作系统：centos7
- Docker版本：26.1.3
- 系统登录页面显示的 ARL 版本:2.6.2

## 复现步骤

请提供重现问题所需的详细步骤。

![1716280109231](https://github.com/Aabyss-Team/ARL/assets/170181877/0600eb19-236f-472a-b834-9fa7e30ca6f0)

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by AabyssZG** [comment]
如果采用Docker拉取安装，试试新密码：honmashironeko

**Comment by 397332130** [comment]
您好，感谢您的回答，是拉取安装的没错，但使用新密码仍然提示错误





------------------ 原始邮件 ------------------
发件人: 曾哥 ***@***.***&gt;
发送时间: 2024年5月21日 16:54
收件人: Aabyss-Team/ARL ***@***.***&gt;
抄送: 397332130 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Aabyss-Team/ARL] 登录ARL使用用户名admin密码arlpass，提示用户名或密码错误，重置密码提示没有arl_mongodb这个容器，请问如何解决 (Issue #10)





 
如果采用Docker拉取安装，试试新密码：honmashironeko

**Comment by 397332130** [comment]
> 如果采用Docker拉取安装，试试新密码：honmashironeko

您好，感谢您的回答，是拉取安装的没错，但使用新密码honmashironeko仍然提示错误

**Comment by AabyssZG** [comment]
请提供一下你pull拉取的docker镜像名

**Comment by 397332130** [comment]
> 请提供一下你pull拉取的docker镜像名
第一次拉取普通版arl-docker，尝试2个密码提示错误，删除容器后重新拉取魔改2的arl-docker-all，尝试2个密码仍提示错误。

**Comment by AabyssZG** [comment]
我这边拉取了镜像 `arl-docker`，通过 `arlpass` 成功登录了平台，师傅再试试看

**Comment by 397332130** [comment]
> 我这边拉取了镜像 ，通过 成功登录了平台，师傅再试试看`arl-docker``arlpass`

非常感谢！！重新拉取，使用密码arlpass登录成功了，不知道第一次提示错误是啥原因

**Comment by AabyssZG** [comment]
好的，有问题欢迎再提 `issue`，感谢师傅的关注和支持~
