### ISSUE TITLE
docker-arl-all的版本账号密码无法登录

### ISSUE THREAD

**Issue by piccheaszd** [Aabyss-Team/ARL#12]
## 描述问题
使用admin账户名
密码为arlpass和honmashironeko都不成功
同时如果想通过mongo更改也不成功
![image](https://github.com/Aabyss-Team/ARL/assets/130952013/138f6ace-bc6a-4054-8da5-6aeb1b8dc345)

请在此处提供对问题的清晰而简洁的描述。

## 环境信息

- 操作系统：Linux kali 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.6.15-2kali1 (2024-05-17) x86_64 GNU/Linux
- Docker版本：Docker version 26.1.3, build b72abbb
- 系统登录页面显示的 ARL 版本: 2.6.2

**Comment by piccheaszd** [comment]
顺便说下我踩过的坑。希望如果有人和我一样可以不用浪费时间。我直接运行docker run后面的/usr/sbin/init是无效的，也就导致了没有systemctl，无法开启那几个服务，arl-web，nginx，mongod等都不行。systemctl可以用用github上的一个systemctl代替方案解决。其他服务就在systemctl能用后开启即可。rabbitmq也需要开启后才能再去用那四条命令来添加。
nginx没开启表现形式是不能连上5003端口
mongod没开启表现形式是timeout 12000ms
systemctl没替换表现形式是无法获取dbus
以上是docker的，在我docker无法成功后装了centos7去用，centos7相较于docker没什么坑只有一点需要注意，nginx开启时要先关闭selinux
太迟了可能说的不是很清楚，早上醒来后我会整理一下对应需要的命令顺序。
我现在看后台日志似乎没什么别的问题了，就是还没登录成功。

**Comment by hengxin007** [comment]
Debian10 docker搭好后也是密码错误，arlpass和honmashironeko都不成功，后来啥也没干，重新搭建一编，使用arlpass进去，但是依然有问题，会提示 timeout of 12000ms exceeded

**Comment by piccheaszd** [comment]
还有一个问题，docker stop后再重启就不能用了。我看了下是/usr/sbin/init会显示service全是inactive dead，自然网络也寄了。不能和宿主机联通。虽然端口占着但是没有用。我不是很懂要启动哪些对应的项，只能是再一次docker run然后再一项项手动启动。发现两个点，一个是没有替换systemctl时候，运行/usr/sbin/init的显示是几个可选数字，而且我记得234好像几个并列在某个选项中都是不能用的，更换后就比较正常。但是我想把做过更改的docker commit后再去同样的docker run也不能成功，也是显示service全是inactive dead。我现在再搭一次，会把中间步骤发出来

**Comment by piccheaszd** [comment]
> 还有一个问题，docker stop后再重启就不能用了。我看了下是/usr/sbin/init会显示service全是inactive dead，自然网络也寄了。不能和宿主机联通。虽然端口占着但是没有用。我不是很懂要启动哪些对应的项，只能是再一次docker run然后再一项项手动启动。发现两个点，一个是没有替换systemctl时候，运行/usr/sbin/init的显示是几个可选数字，而且我记得234好像几个并列在某个选项中都是不能用的，更换后就比较正常。但是我想把做过更改的docker commit后再去同样的docker run也不能成功，也是显示service全是inactive dead。我现在再搭一次，会把中间步骤发出来

![image](https://github.com/Aabyss-Team/ARL/assets/130952013/eaa999b3-84fd-44cd-ab17-fe5e3b9b7963)

**Comment by piccheaszd** [comment]
好像commit这样就行？
![image](https://github.com/Aabyss-Team/ARL/assets/130952013/fdf40409-75ed-4df8-9f02-6bcfede15211)

**Comment by piccheaszd** [comment]
先进入container替换systemctl
wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/bin/systemctl
随后再commit一个新的image
docker commit -c "CMD ['/usr/bin/systemctl']" \
    -m "<comment>" <container> <new-image>
再关闭之前的容器，防止端口占用，启动新image
sudo docker run -d -p 5003:5003 --name <container id >--privileged=true <image id> /usr/bin/systemctl
进入新container后
mongod --dbpath /data/GeoLite2/ --fork --logpath /var/log/mongodb/
就可以到登录页面了，剩下的密码我还是没有

**Comment by piccheaszd** [comment]
> 顺便说下我踩过的坑。希望如果有人和我一样可以不用浪费时间。我直接运行docker run后面的/usr/sbin/init是无效的，也就导致了没有systemctl，无法开启那几个服务，arl-web，nginx，mongod等都不行。systemctl可以用用github上的一个systemctl代替方案解决。其他服务就在systemctl能用后开启即可。rabbitmq也需要开启后才能再去用那四条命令来添加。 nginx没开启表现形式是不能连上5003端口 mongod没开启表现形式是timeout 12000ms systemctl没替换表现形式是无法获取dbus 以上是docker的，在我docker无法成功后装了centos7去用，centos7相较于docker没什么坑只有一点需要注意，nginx开启时要先关闭selinux 太迟了可能说的不是很清楚，早上醒来后我会整理一下对应需要的命令顺序。 我现在看后台日志似乎没什么别的问题了，就是还没登录成功。

所以这个其实是不需要的，原本service应该在入口点后自动执行。我觉得是某些原因/usr/sbin/init作为入口点不能使用。改换/usr/local/systemctl后作为入口点就行了。

**Comment by piccheaszd** [comment]
登录问题已解决
mongo 修改那张用户表其实不需要登录。不能登录原因是表是空的
![image](https://github.com/Aabyss-Team/ARL/assets/130952013/9edfab03-ca19-4046-a5d7-ebd5f65796e7)
加上数据就行
