### ISSUE TITLE
docker 仓库也删了怎么快速搭建

### ISSUE THREAD

**Issue by okoling** [Aabyss-Team/ARL#2]
docker 仓库也删了怎么快速搭建，有备份吗？

**Comment by Christ1na1** [comment]
> docker仓库也删了怎么快速搭建，有备份吗？

你找到解决方法了吗

**Comment by b1ank1108** [comment]
https://github.com/1c3z/ARL-NPoC
https://github.com/1c3z/arl_files

docker/work里面有Dockerfile

**Comment by futalk** [comment]
https://blog.putdown.top/archives/arl-deng-ta-shan-ku-hou-shi-yong-dockerda-jian-arl-deng-ta

**Comment by b1ank1108** [comment]
> > https://github.com/1c3z/ARL-NPoC https://github.com/1c3z/arl_files
> > docker/work里面有Dockerfile
> 
> 被删了？

坏 被发现了

**Comment by know35** [comment]
必须要别的人docker备份才能搭建吗

**Comment by AabyssZG** [comment]
**如需自己构建本项目，在拉取时记得将 `TophantTechnology/ARL` 和 `1c3z/ARL-NPoC` 替换为 `Aabyss-Team/ARL` 和 `Aabyss-Team/ARL-NPoC`**

**Comment by AabyssZG** [comment]
**如需自己构建本项目，在拉取时记得将 `TophantTechnology/ARL` / `1c3z/ARL-NPoC` / `1c3z/arl_files` 这三个字符串替换为 `Aabyss-Team/ARL` / `Aabyss-Team/ARL-NPoC` / `Aabyss-Team/arl_files`**

**Comment by Joinweike** [comment]
我源码安装nginx服务启动不起来怎么办

**Comment by AabyssZG** [comment]
> 我源码安装nginx服务启动不起来怎么办

#### 安装问题1：没有可用软件包 nginx

在命令行执行：

```
sudo yum -y install epel-release
sudo yum makecache
sudo yum install nginx* --skip-broken
```

这个是玄学问题，有时候能碰到这个报错，有时候又碰不到。。

#### 安装问题2：脚本跑起来后运行任务显示 error

要赋予 `/opt/ARL/app/tools/massdns` 目录的执行权限（给777也行）

```
cd /opt/ARL/app/tools/
sudo chmod +x massdns
```

然后就可以愉快的玩耍了~~~

**Comment by AabyssZG** [comment]
Docker安装过程如下：

```
//安装docker
yum -y install docker

//启动Docker服务
systemctl start docker

//拉取Docker镜像
docker pull honmashironeko/arl-docker

//运行Docker容器
docker run -d -p 5003:5003 --name arl --privileged=true honmashironeko/arl-docker /usr/sbin/init
```

- 接下来，前往ARL-Web页面：https://IP:5003/
- 账号：admin，密码：arlpass
- Ubuntu 下可以直接执行 `apt-get install docker.io docker-compose -y` 安装相关依赖

**Comment by Grass1** [comment]
@AabyssZG 源码安装提示没有xing模块怎么处理啊
ERROR: No matching distribution found for xing

**Comment by AabyssZG** [comment]
> @AabyssZG 源码安装提示没有xing模块怎么处理啊 ERROR: No matching distribution found for xing

源码安装使用 `CentOS 7.9` 是没问题的，我们这边安装过程中并没有出现xing模块问题
具体原因还需要再排查一下，因为我们没出现，所以目前并不清楚解决方案

**Comment by fubxx** [comment]
> https://blog.putdown.top/archives/arl-deng-ta-shan-ku-hou-shi-yong-dockerda-jian-arl-deng-ta

我去 这博客挂了

**Comment by AabyssZG** [comment]
> > https://blog.putdown.top/archives/arl-deng-ta-shan-ku-hou-shi-yong-dockerda-jian-arl-deng-ta
> 
> 我去 这博客挂了

看了一下，这个链接需要代理才能访问。。

**Comment by futalk** [comment]
> > > [https://blog.putdoun.top/archives/earl-deng-ta-shan-ku-hu-shi-young-dokarda-jian-earl-deng-ta](https://blog.putdown.top/archives/arl-deng-ta-shan-ku-hou-shi-yong-dockerda-jian-arl-deng-ta)
> > 
> > 
> > 我去 这博客挂了
> 
> 看了一下，这个链接需要代理才能访问。。

在修了 在修炼

**Comment by futalk** [comment]
> > > [https://blog.putdoun.top/archives/earl-deng-ta-shan-ku-hu-shi-young-dokarda-jian-earl-deng-ta](https://blog.putdown.top/archives/arl-deng-ta-shan-ku-hou-shi-yong-dockerda-jian-arl-deng-ta)
> > 
> > 
> > 我去 这博客挂了
> 
> 看了一下，这个链接需要代理才能访问。。

在修了  在修了
