### ISSUE TITLE
初始密码错误

### ISSUE THREAD

**Issue by xxxxxxovo** [Aabyss-Team/ARL#29]
![image](https://github.com/Aabyss-Team/ARL/assets/142147430/945fe2e7-e48c-4059-8204-6d0774beaaa6)

**Comment by xxxxxxovo** [comment]
看错了，误以为是这个，多有打扰，抱歉
![image](https://github.com/Aabyss-Team/ARL/assets/142147430/b2541a66-97db-4f30-bbc0-e2076baa11c4)

**Comment by AabyssZG** [comment]
没事，有问题欢迎继续提Issues
