### ISSUE TITLE
源代码安装里面的脚本是空的啊，ERROR 404

### ISSUE THREAD

**Issue by cyuma007** [Aabyss-Team/ARL#3]
## 描述问题

请在此处提供对问题的清晰而简洁的描述。

## 环境信息

- 操作系统：
- Docker版本：
- 系统登录页面显示的 ARL 版本:

### 错误输出

请执行以下命令，并提供输出结果：

`docker compose ps`
截图：

`docker compose logs -f  --tail=10`
截图：

`tail -f arl_worker.log`
截图：

## 复现步骤

请提供重现问题所需的详细步骤。

1. 步骤一
2. 步骤二
3. 步骤三

## 预期行为

请描述您预期发生的事情。

## 实际行为

请描述实际发生的事情。

## 附加上下文

在此处提供其他有关问题的任何其他上下文。

## 卸载或者重装文档。
https://tophanttechnology.github.io/ARL-doc/faq/#12-docker

**Comment by AabyssZG** [comment]
**如需自己构建本项目，在拉取时记得将 `TophantTechnology/ARL` 和 `1c3z/ARL-NPoC` 替换为 `Aabyss-Team/ARL` 和 `Aabyss-Team/ARL-NPoC`**

**Comment by AabyssZG** [comment]
**如需自己构建本项目，在拉取时记得将 `TophantTechnology/ARL` / `1c3z/ARL-NPoC` / `1c3z/arl_files` 这三个字符串替换为 `Aabyss-Team/ARL` / `Aabyss-Team/ARL-NPoC` / `Aabyss-Team/arl_files`**

**Comment by Pikkk528** [comment]
改了也是空的，就没有releases，返回都是404

**Comment by AabyssZG** [comment]
**在 `CentOS7` 系统上，直接拉取运行本项目内的 `misc/setup-arl.sh` 即可安装源码，请看 [10# 源码安装](https://github.com/Aabyss-Team/ARL?tab=readme-ov-file#10-%E6%BA%90%E7%A0%81%E5%AE%89%E8%A3%85) 板块**

**Comment by AabyssZG** [comment]
Docker安装过程如下：

```
//安装docker
yum -y install docker

//启动Docker服务
systemctl start docker

//拉取Docker镜像
docker pull honmashironeko/arl-docker

//运行Docker容器
docker run -d -p 5003:5003 --name arl --privileged=true honmashironeko/arl-docker /usr/sbin/init
```

- 接下来，前往ARL-Web页面：https://IP:5003/
- 账号：admin，密码：arlpass
- Ubuntu 下可以直接执行 `apt-get install docker.io docker-compose -y` 安装相关依赖
